#spring.application.name=timesheet
application:
  logging:
    enabled: true
    level: WARN
    PrintArgs: true

server:
  port: 8080
spring:
  application:
    name: timesheet-rest
    datasource:
      url: jdbc:mysql://localhost:3306/mydb
      username: sa
      password:
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true